network:
  version: 2
  renderer: networkd
  ethernets:
    eno7:
      dhcp4: false
      addresses:
      - 192.168.10.10/24
      gateway4: 192.168.10.1
      nameservers:
        addresses:
        - 8.8.8.8
        - 8.8.4.4
      routes:
      - to: 0.0.0.0/0
        via: 192.168.10.1
        metric: 100
    eno10:
      dhcp4: false
      addresses:
      - 192.168.20.10/24
      gateway4: 192.168.20.1
      nameservers:
        addresses:
        - 1.1.1.1
        - 1.0.0.1
      routes:
      - to: 0.0.0.0/0
        via: 192.168.20.1
        metric: 200
    eno8:
      dhcp4: false
      addresses:
      - 192.168.300.200/24
      gateway4: 192.168.300.1
      nameservers:
        addresses:
        - 8.8.8.8
        - 8.8.4.4
      routes:
      - to: 0.0.0.0/0
        via: 192.168.300.1
        metric: 700
    eno11:
      dhcp4: false
      addresses:
      - 192.168.40.10/24
      gateway4: 192.168.40.1
      nameservers:
        addresses:
        - 208.67.222.222
        - 208.67.220.220
      routes:
      - to: 0.0.0.0/0
        via: 192.168.40.1
        metric: 400
